version: '3.7'
services:
  # nginx:
  #   container_name: ffcsa_nginx
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/app/static
  #     - media_volume:/app/media
  #     - ./nginx/staging:/etc/nginx/conf.d
  #   ports:
  #     - 8080:80
  #     # - 443:443
  #   depends_on:
  #     - django_gunicorn
  
  django_gunicorn:
    container_name: ffcsa_web
    build:
      context: .
      dockerfile: ./docker/gunicorn.staging.Dockerfile
    restart: always
    command: gunicorn --workers=4 ffcsa.wsgi:application --bind 0.0.0.0:8000 --timeout 100 --reload
    env_file: .env
    volumes:
      - .:/app
      - ./static:/app/static
      - media_volume:/app/media
      # - static_volume:/app/static
    ports: 
      - 8000:8000
    depends_on: 
      - mysql

  mysql:
    container_name: ffcsa_db
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: U7srFFgcmtzE
      MYSQL_DATABASE: ffcsa
      # MYSQL_USER: ffcsa
      # MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306


volumes:
  db_data:
  static_volume:
  media_volume: