# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20200609_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='no_plastic_bags',
        ),
        migrations.AddField(
            model_name='order',
            name='plastic_bags',
            field=models.BooleanField(default=False, verbose_name='Use Plastic Bags'),
        ),
    ]
