# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-17 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20201030_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_dairy',
            field=models.BooleanField(default=False, help_text='This is used to prevent unauthorized users from ordering raw dairy products', verbose_name='Is Raw Dairy'),
        ),
    ]
