# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_productseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='season',
            field=models.ManyToManyField(to='shop.ProductSeason'),
        ),
    ]
