# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_productvariation_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='season',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='seasons',
            field=models.ManyToManyField(related_name='seasons', to='shop.ProductSeason'),
        ),
    ]
