# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_auto_20210121_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('code', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variations', to='shop.ProductVariationUnit'),
        ),
    ]
