# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20210122_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productseason',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='productvariationunit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_products', to='shop.Category', verbose_name='Product categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='seasons', to='shop.ProductSeason'),
        ),
    ]
