# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-04-17 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20211113_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Description'),
        ),
    ]
