# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-04-21 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20210216_1628'),
        ('shop', '0057_auto_20220420_2013'),
    ]

    operations = [
    ]
