# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-07-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('shop', '0059_auto_20220529_0702'), ('shop', '0061_merge_20220618_0547'), ('shop', '0062_auto_20220618_1358'), ('shop', '0063_auto_20220618_1409'), ('shop', '0064_auto_20220618_1420'), ('shop', '0065_auto_20220618_1429'), ('shop', '0066_auto_20220618_1440'), ('shop', '0067_auto_20220619_1037')]

    dependencies = [
        ('shop', '0058_merge_20220420_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set([]),
        ),
        migrations.AlterModelOptions(
            name='productseason',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='productvariationunit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='product',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='seasons', to='shop.ProductSeason'),
        ),
    ]
