# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-07-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20220529_0702_squashed_0067_auto_20220619_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order_on_invoice',
            field=models.IntegerField(default=0, help_text='Order this category will be printed on invoices.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='category_products', to='shop.Category', verbose_name='Product categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_on_invoice',
            field=models.FloatField(blank=True, default=0, help_text="Order this product will be printed on invoices. If set, this will override the product's category order_on_invoice setting.", null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='unit',
            field=models.CharField(blank=True, help_text='Displays after the prices. Ex. $20 / {unit}', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='weight',
            field=models.CharField(blank=True, help_text='Displays on the bottom left corner of the product image', max_length=200, null=True, verbose_name='Amount/Weight'),
        ),
    ]
