# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-18 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20220529_0702'),
        ('shop', '0060_auto_20220618_0702'),
    ]

    operations = [
    ]
