# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_merge_20220618_0547'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='product',
            #name='unit',
            #field=models.CharField(blank=True, max_length=200, null=True),
        #),
        #migrations.AddField(
            #model_name='product',
            #name='weight',
            #field=models.CharField(blank=True, max_length=200, null=True),
        #),
    ]
