# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20220618_1409'),
    ]

    operations = [
     #migrations.AddField(
            #model_name='productvariation',
            #name='weight',
            #field=models.CharField(blank=True, max_length=200, null=True),
        #),
        migrations.AlterField(
            model_name='productvariation',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set([]),
        ),
    ]
