# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20220618_1420'),
    ]

    operations = [
       #migrations.CreateModel(
            #name='ProductSeason',
            #fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('slug', models.SlugField(blank=True, max_length=200)),
                #('name', models.SlugField(max_length=200)),
            #],
        #),
    ]
