# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20220618_1429'),
    ]

    operations = [
     #migrations.RemoveField(
            #model_name='productvariation',
            #name='seasons',
        #),
        #migrations.AddField(
            #model_name='product',
            #name='seasons',
            #field=models.ManyToManyField(related_name='seasons', to='shop.ProductSeason'),
        #),
    ]
