# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20220618_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productseason',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='productvariationunit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='product',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='seasons', to='shop.ProductSeason'),
        ),
    ]
