# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0054_auto_20220529_0702'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='payment',
            #name='pending',
        #),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Failed', 'Failed')], default='Accepted', max_length=50),
        ),
    ]
