# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-07-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcsa_core', '0054_auto_20220529_0702_squashed_0055_auto_20220619_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plastic_bags',
            field=models.BooleanField(default=False, help_text='Please pack small items in bags.'),
        ),
    ]
