name: Deploy Prod

on:
  push:
    branches: [ prod ]

jobs:
  build:

    runs-on: [self-hosted, prod]
#    defaults:
#      run:
#        working-directory: /home/ffcsa/webapps/ffcsa
        
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Open Web Client Directory
      run: |
        cd /home/ffcsa/
        ls -la

#    # Build frontend
#    - name: Build frontend
#      run: npm run prod


#    - name: Pull changes
#    - run: git pull git@github.com:ewingrj/ffcsa.git prod
#
#    - name: Build frontend
#      run: npm run prod
#
#    - name: Activate virtualenv
#      run: pyenv activate ffcsa_prod
#
#    - name: Collect Static
#      run: python manage.py collectstatic
#
#    - name: Restart Gunicorn
#      run: sudo supervisorctl restart gunicorn_ffcsa_prod
#
#    - name: Restart nginx
#      run: service nginx restart
