name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ffcsa/app/ffcsa
        
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    
    # Pull changes
    - run: git pull git@github.com:ewingrj/ffcsa.git staging
    # - run: git pull https://muhamedyoussef:${{ secrets.FFCSA }}@github.com/ewingrj/ffcsa.git feature/api_with_vue

    # Build frontend
    - name: Build frontend
      run: npm run prod

    # Collect static
    - name: Collect Static
      run: docker exec ffcsa_web python manage.py collectstatic --no-input
