name: Deploy Staging

on:
  push:
    branches: [ feature/api_with_vue ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ffcsa/app/ffcsa
        
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        repository:  ewingrj/ffcsa
        # token: ${{ secrets.FFCSA }}
        token: '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'
    
    # Pull changes
    - run: git pull https://muhamedyoussef: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@github.com/ewingrj/ffcsa.git feature/api_with_vue

    # Build frontend
    - name: Build frontend
      run: npm run prod

    # Collect static
    - name: Collect Static
      run: docker exec ffcsa_web python manage.py collectstatic --no-input